### ISSUE TITLE
定时任务没有执行

### ISSUE THREAD

**Issue by smartwjw** [0xbug/Hawkeye#10]
macOS 10.12 系统
控制台没有任何关于定时任务的输出。

**Comment by 0xbug** [comment]
crontab -l的结果呢

**Comment by smartwjw** [comment]
```bash
*/5 * * * * /xxx/Hawkeye/venv/bin/python /xxx/Hawkeye/spider.py 1 4 # Hawkeye
```

**Comment by smartwjw** [comment]
看了下 cron 的输出:

```
Traceback (most recent call last):
  File "/Users/junwei/projects/opensource/Hawkeye/spider.py", line 199, in <module>
    crawl(query)
  File "/Users/junwei/projects/opensource/Hawkeye/spider.py", line 82, in crawl
    print('\u767b\u5f55\u5931\u8d25')
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-3: ordinal not in range(128)
```

**Comment by 0xbug** [comment]
py2？

**Comment by smartwjw** [comment]
python 3, 加 venv

**Comment by 0xbug** [comment]
直接执行下cron中的命令试试有无报错

**Comment by smartwjw** [comment]
提示 
“登录失败”

我没有配置 github 的账户密码，github 有允许公开请求的配额吧？

**Comment by 0xbug** [comment]
未登录不能直接搜索代码

**Comment by smartwjw** [comment]
我开了 two factor auth, 直接配置账户密码估计不能用，代码可否支持 access token ?

**Comment by 0xbug** [comment]
专门新建个账户吧

**Comment by smartwjw** [comment]
多谢。

**Comment by smartwjw** [comment]
配置了用户名之后可以了，不过抓取了一部分之后报错：

```
Traceback (most recent call last):
  File "/xxx/Hawkeye/spider.py", line 200, in <module>
    crawl(query)
  File "/xxxx/Hawkeye/spider.py", line 86, in crawl
    nodes = tree.xpath(get_conf('Leakage', 'NODES'))
AttributeError: 'NoneType' object has no attribute 'xpath'
```

**Comment by 0xbug** [comment]
print(resp.text)试试
