### ISSUE TITLE
无法爬关键词，报错

### ISSUE THREAD

**Issue by BouteilleKwok** [0xbug/Hawkeye#45]
配置页面跳 Error: Request failed with status code 500 错误
后台报错误：
[2018-04-26 09:13:58,515] ERROR in app: Exception on /api/setting/cron [GET]
Traceback (most recent call last):
  File "/opt/Hawkeye/venv/lib/python3.6/site-packages/flask/app.py", line 1612, in full_dispatch_request
    rv = self.dispatch_request()
  File "/opt/Hawkeye/venv/lib/python3.6/site-packages/flask/app.py", line 1598, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/opt/Hawkeye/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/opt/Hawkeye/venv/lib/python3.6/site-packages/flask/views.py", line 84, in view
    return self.dispatch_request(*args, **kwargs)
  File "/opt/Hawkeye/venv/lib/python3.6/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "Hawkeye.py", line 279, in get
    return jsonify({'status': 200, 'msg': '\u83b7\u53d6\u4fe1\u606f\u6210\u529f', 'result': read_cron()})
  File "Hawkeye.py", line 328, in read_cron
    user_cron = CronTab(user=True)
  File "/opt/Hawkeye/venv/lib/python3.6/site-packages/crontab.py", line 216, in __init__
    self.read(tabfile)
  File "/opt/Hawkeye/venv/lib/python3.6/site-packages/crontab.py", line 263, in read
    (out, err) = open_pipe(CRONCMD, l='', **self.user_opt).communicate()
  File "/opt/Hawkeye/venv/lib/python3.6/site-packages/crontab.py", line 178, in open_pipe
    return sp.Popen(args, stdout=sp.PIPE, stderr=sp.PIPE)
  File "/usr/local/lib/python3.6/subprocess.py", line 958, in __init__
    restore_signals, start_new_session)
  File "/usr/local/lib/python3.6/subprocess.py", line 1555, in _execute_child
    raise child_exception_type(errno_num, err_msg)
OSError: [Errno 8] Exec format error

**Comment by 0xbug** [comment]
当前用户？执行下crontab -l 看下

**Comment by 0xbug** [comment]
点击那个确认按钮了吗？

**Comment by BouteilleKwok** [comment]
确认？ 时间和页面设置么？ 点确认 就跳500那个错误提示。登录页面的确认是没问题可以登录进来

**Comment by 0xbug** [comment]
先手动加定时任务吧

crontab -e

```
*/20 * * * * /opt/Hawkeye/venv/bin/python /opt/Hawkeye/spider.py 1 2 # Hawkeye
```

**Comment by BouteilleKwok** [comment]
已修复 谢谢，原来是没有装crontab，重新安装了crontab
