### ISSUE TITLE
新版更新后中文标签乱码

### ISSUE THREAD

**Issue by lx277856602** [0xbug/Hawkeye#49]
如题,中文标签显示乱码, 导致抓取出错.

--- Logging error ---
Traceback (most recent call last):
  File "/usr/lib64/python3.4/logging/__init__.py", line 980, in emit
    stream.write(msg)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 66-69: ordinal not in range(128)
Call stack:
  File "spider.py", line 265, in <module>
    crawl(query)
  File "spider.py", line 114, in crawl
    logger.info('start crawl: tag is {}, page is {}'.format(query.get('tag'), page))
Message: 'start crawl: tag is \u65b9\u5fb7\u8bc1\u5238, page is 14'
Arguments: ()
2018-05-31 16:32:40,099 [Hawkeye] [INFO] start crawl: tag is \u65b9\u5fb7\u8bc1\u5238, page is 15

**Comment by lx277856602** [comment]
已解决,请无视
