### ISSUE TITLE
你好，重新打包时出现以下错误请问如何解决

### ISSUE THREAD

**Issue by Mr89898** [0xbug/Hawkeye#52]
ERROR in ./src/main.js
Module build failed: ReferenceError: Unknown plugin "transform-vue-jsx" specified in "/root/Hawkeye/client/.babelrc" at 0, attempted to resolve relative to "/root/Hawkeye/client"
    at /root/Hawkeye/client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:180:17
    at Array.map (native)
    at Function.normalisePlugins (/root/Hawkeye/client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:158:20)
    at OptionManager.mergeOptions (/root/Hawkeye/client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:234:36)
    at OptionManager.init (/root/Hawkeye/client/node_modules/babel-core/lib/transformation/file/options/option-manager.js:368:12)
    at File.initOptions (/root/Hawkeye/client/node_modules/babel-core/lib/transformation/file/index.js:212:65)
    at new File (/root/Hawkeye/client/node_modules/babel-core/lib/transformation/file/index.js:135:24)
    at Pipeline.transform (/root/Hawkeye/client/node_modules/babel-core/lib/transformation/pipeline.js:46:16)
    at transpile (/root/Hawkeye/client/node_modules/babel-loader/lib/index.js:50:20)
    at Object.module.exports (/root/Hawkeye/client/node_modules/babel-loader/lib/index.js:173:20)

  Build failed with errors.

**Comment by 0xbug** [comment]
npm install 了吗?
二次开发的问题放到一个issues里讨论

**Comment by Mr89898** [comment]
谢谢，我已经自行解决了这个问题
