### ISSUE TITLE
你好开启basic模式，运行时出现如下情况是哪里出现错误

### ISSUE THREAD

**Issue by Mr89898** [0xbug/Hawkeye#53]
Traceback (most recent call last):
  File "Hawkeye.py", line 54, in <module>
    app.config['BASIC_AUTH_PASSWORD'] = get_conf('Auth', 'PASSWORD')
  File "Hawkeye.py", line 28, in get_conf
    return config.get(section=section, option=option)
  File "/usr/local/bin/python3/lib/python3.5/configparser.py", line 798, in get
    d)
  File "/usr/local/bin/python3/lib/python3.5/configparser.py", line 396, in before_get
    self._interpolate_some(parser, option, L, value, section, defaults, 1)
  File "/usr/local/bin/python3/lib/python3.5/configparser.py", line 445, in _interpolate_some
    "found: %r" % (rest,))
configparser.InterpolationSyntaxError: '%' must be followed by '%' or '(', found: '%f'

**Comment by 0xbug** [comment]
密码中有%吗

**Comment by Mr89898** [comment]
有%号

**Comment by 0xbug** [comment]
需要写成%%

**Comment by Mr89898** [comment]
Traceback (most recent call last):
  File "Hawkeye.py", line 9, in <module>
    import configparser
  File "/usr/local/bin/python3/lib/python3.5/configparser.py", line 184
    self.section = section
       ^
SyntaxError: invalid syntax
按照要求密码写成两个%%号，但是还是报了如下错误
