### ISSUE TITLE
配置页面-报错Error：Request failed with status code 500

### ISSUE THREAD

**Issue by BouteilleKwok** [0xbug/Hawkeye#64]
点击配置，就会显示错误500

记录显示：
172.17.0.1 - - [14/Aug/2018 09:41:21] "GET /api/setting/query HTTP/1.1" 200 -
172.17.0.1 - - [14/Aug/2018 09:41:21] "GET /api/setting/blacklist HTTP/1.1" 200 -
172.17.0.1 - - [14/Aug/2018 09:41:21] "GET /api/setting/notice HTTP/1.1" 200 -
[2018-08-14 09:41:21,489] ERROR in app: Exception on /api/setting/cron [GET]
Traceback (most recent call last):
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/lib64/python2.7/site-packages/flask/app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/usr/lib64/python2.7/site-packages/flask_restful/__init__.py", line 480, in wrapper
    resp = resource(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/flask/views.py", line 88, in view
    return self.dispatch_request(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/flask_restful/__init__.py", line 595, in dispatch_request
    resp = meth(*args, **kwargs)
  File "Hawkeye.py", line 279, in get
    return jsonify({'status': 200, 'msg': '获取信息成功', 'result': read_cron()})
  File "Hawkeye.py", line 328, in read_cron
    user_cron = CronTab(user=True)
TypeError: __init__() got an unexpected keyword argument 'user'
172.17.0.1 - - [14/Aug/2018 09:41:21] "GET /api/setting/cron HTTP/1.1" 500 -

**Comment by BouteilleKwok** [comment]
已解决，是python2和3版本的问题
